DELETE http://localhost:3003/api/blogs/64f8520d9237f023915fb18f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjY0NTFmZGJlN2RlNjdhNDllNjM0OTllYSIsImlhdCI6MTY5Mzk5NTAwMn0.c7oWFBLK-ayZmZDSL-VqZNTvj9uxQgXDAndk5fxUntc

