POST http://localhost:3003/api/blogs
Content-Type: application/json

{

        "title": "React patterns",
        "author": "Michael Chan",
        "url": "https://reactpatterns.com/",
        "user": "6450bdc820b134f85aaf02de"
 

   
   
}