POST http://localhost:3003/api/blogs 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjY0NTFmZGJlN2RlNjdhNDllNjM0OTllYSIsImlhdCI6MTY5Mzk5NTAwMn0.c7oWFBLK-ayZmZDSL-VqZNTvj9uxQgXDAndk5fxUntc

{
"title": "Kikkare", "author": "Antti Mäkinen-Kakkanen", "url": "www.antti.com"
}